controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Login:
   path: /register
   controller: App\Controller\RegisterController::__invoke
   methods: [POST]
